'use client';

import { useState, useEffect, useRef } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import { Button } from '@/components/ui/button';
import { FoundryAIOutput, RefinementState } from '@/types';
import { 
  Target, Users, Wrench, Layers, Hammer, DollarSign, 
  ThumbsUp, ThumbsDown, CheckCircle, Clock, Check,
  Sparkles, Gem, ArrowRight, Wand2, Zap, Crown,
  TrendingUp, PieChart, BarChart3, Search, AlertTriangle,
  Rocket, Brain, Lightbulb, ChevronRight,
  Copy, Check as CheckIcon, Download, Share2, FileText, Code2
} from 'lucide-react';

interface OutputDisplayProps {
  output: FoundryAIOutput;
  onFeedback: (isHelpful: boolean) => void;
  onRefine: () => void;
  refinementState: RefinementState;
}

const refinementBadges = [
  { icon: Sparkles, label: "Very Well Planned", gradient: "from-blue-500 to-cyan-500" },
  { icon: Gem, label: "Meticulously Crafted", gradient: "from-violet-500 to-fuchsia-500" },
  { icon: Zap, label: "Very Well Structured", gradient: "from-amber-500 to-orange-500" },
  { icon: Crown, label: "Masterclass Level", gradient: "from-emerald-500 to-teal-500" },
];

const sectionIcons = {
  marketResearch: TrendingUp,
  mvpFeatures: Wrench,
  techStack: Layers,
  buildPlan: Hammer,
  monetization: DollarSign,
};

export function OutputDisplay({ output, onFeedback, onRefine, refinementState }: OutputDisplayProps) {
  const [feedbackSubmitted, setFeedbackSubmitted] = useState(false);
  const [copiedSection, setCopiedSection] = useState<string | null>(null);
  const [showExportMenu, setShowExportMenu] = useState(false);
  const exportMenuRef = useRef<HTMLDivElement>(null);
  const [expandedSections, setExpandedSections] = useState<Record<string, boolean>>({
    marketResearch: true,
    mvpFeatures: true,
    techStack: true,
    buildPlan: true,
    monetization: true,
  });

  const handleFeedback = (isHelpful: boolean) => {
    onFeedback(isHelpful);
    setFeedbackSubmitted(true);
  };

  // Close export menu when clicking outside
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (exportMenuRef.current && !exportMenuRef.current.contains(event.target as Node)) {
        setShowExportMenu(false);
      }
    };

    if (showExportMenu) {
      document.addEventListener('mousedown', handleClickOutside);
    }

    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
    };
  }, [showExportMenu]);

  const copyToClipboard = async (text: string, section: string) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopiedSection(section);
      setTimeout(() => setCopiedSection(null), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  const exportAsMarkdown = () => {
    const markdown = `# ${output.toolIdea}

## Target User
${output.targetUser}

## Problem Statement
${output.problemStatement}

## Market Research
- **TAM**: ${output.marketResearch?.tam || 'N/A'}
- **SAM**: ${output.marketResearch?.sam || 'N/A'}
- **SOM**: ${output.marketResearch?.som || 'N/A'}
- **Growth Rate**: ${output.marketResearch?.marketGrowthRate || 'N/A'}

### Key Trends
${output.marketResearch?.keyTrends?.map(t => `- ${t}`).join('\n') || '- N/A'}

### Competitors
${output.marketResearch?.competitorAnalysis?.map(c => `- **${c.name}**: ${c.marketShare} market share`).join('\n') || '- N/A'}

## MVP Features
${output.mvpFeatures.map((f, i) => `${i + 1}. ${f}`).join('\n')}

## Tech Stack
${output.techStack.map(t => `- **${t.category}**: ${t.tool} - ${t.purpose}`).join('\n')}

## Build Plan
${output.buildPlan.map(step => `### Step ${step.step}: ${step.title}
- **Time**: ${step.estimatedTime}
- **Description**: ${step.description}
${step.aiToolAction ? `- **AI Action**: ${step.aiToolAction}` : ''}`).join('\n\n')}

## Monetization Strategy
- **Model**: ${output.monetizationStrategy.model}
- **Pricing**: ${output.monetizationStrategy.pricing}
- **Revenue Estimate**: ${output.monetizationStrategy.revenueEstimate}

### User Acquisition
${output.monetizationStrategy.firstUserTactics.map(t => `- ${t}`).join('\n')}

---
Generated by FoundryAI
`;
    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${(output.ideaName || output.toolIdea || 'plan').replace(/\s+/g, '-').toLowerCase()}-plan.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const exportAsJSON = () => {
    const json = JSON.stringify(output, null, 2);
    const blob = new Blob([json], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${(output.ideaName || output.toolIdea || 'plan').replace(/\s+/g, '-').toLowerCase()}-plan.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const sharePlan = async () => {
    const shareData = {
      title: `FoundryAI Plan: ${output.ideaName || output.toolIdea}`,
      text: `Check out this business plan for "${output.ideaName || output.toolIdea}" - ${(output.problemStatement?.fullStatement || '').slice(0, 100)}...`,
      url: window.location.href,
    };
    
    if (navigator.share) {
      try {
        await navigator.share(shareData);
      } catch (err) {
        console.log('Share cancelled');
      }
    } else {
      copyToClipboard(window.location.href, 'share');
    }
  };

  const toggleSection = (section: string) => {
    setExpandedSections(prev => ({ ...prev, [section]: !prev[section] }));
  };

  const iterationCount = output.refinementMetadata?.iterationCount || refinementState.iterationCount || 0;
  const hasBeenRefined = iterationCount > 0;

  return (
    <div className="space-y-6 fade-in-up">
      {/* Refinement Status Banner */}
      {hasBeenRefined && (
        <Card className="border-primary/20 bg-gradient-to-r from-primary/5 to-primary/10 shadow-lg shadow-primary/5 overflow-hidden">
          <CardContent className="py-5">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-4">
                <div className="relative">
                  <div className="p-3 bg-white rounded-xl shadow-md">
                    <Crown className="w-6 h-6 text-primary" />
                  </div>
                  <div className="absolute -top-1 -right-1 w-5 h-5 bg-gradient-to-br from-amber-400 to-orange-500 rounded-full flex items-center justify-center text-[10px] font-bold text-white">
                    {iterationCount}
                  </div>
                </div>
                <div>
                  <p className="font-semibold text-foreground flex items-center gap-2">
                    <Sparkles className="w-4 h-4 text-primary" />
                    Meticulously-Crafted Output
                  </p>
                  <p className="text-sm text-muted-foreground">
                    {output.refinementMetadata?.refinementFocus?.join(' • ') || 'Comprehensive Enhancement'}
                  </p>
                </div>
              </div>
              <div className="flex gap-2">
                {refinementBadges.slice(0, Math.min(iterationCount, 4)).map((badge, idx) => {
                  const BadgeIcon = badge.icon;
                  return (
                    <div 
                      key={idx}
                      className={`p-2 rounded-lg bg-gradient-to-r ${badge.gradient} shadow-md hover-lift cursor-help`}
                      title={badge.label}
                    >
                      <BadgeIcon className="w-4 h-4 text-white" />
                    </div>
                  );
                })}
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Main Output Card */}
      <Card className="border-border/50 shadow-xl bg-white/90 backdrop-blur-xl overflow-hidden">
        <CardHeader className="pb-6 border-b border-border/50">
          <div className="flex items-start justify-between gap-4">
            <div className="flex items-start gap-4 flex-1">
              <div className="p-3 bg-gradient-to-br from-primary/20 to-primary/5 rounded-xl shadow-sm">
                <Target className="w-6 h-6 text-primary" />
              </div>
              <div className="flex-1">
                <CardTitle className="text-2xl font-bold tracking-tight mb-2">
                  {output.ideaName || output.toolIdea}
                </CardTitle>
                <div className="flex items-center gap-2 text-muted-foreground">
                  <Users className="w-4 h-4" />
                  <span className="text-sm">{output.targetAudience?.description || output.targetUser}</span>
                </div>
              </div>
            </div>
            
            {/* Export & Share Toolbar */}
            <div className="flex items-center gap-2">
              <Button
                variant="ghost"
                size="sm"
                onClick={() => copyToClipboard(`${output.ideaName || output.toolIdea}\n\n${output.problemStatement?.fullStatement || ''}`, 'full')}
                className="gap-1.5"
                title="Copy full plan"
              >
                {copiedSection === 'full' ? (
                  <CheckIcon className="w-4 h-4 text-green-500" />
                ) : (
                  <Copy className="w-4 h-4" />
                )}
                <span className="hidden sm:inline">Copy</span>
              </Button>
              
              <div className="relative" ref={exportMenuRef}>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => setShowExportMenu(!showExportMenu)}
                  className="gap-1.5"
                >
                  <Download className="w-4 h-4" />
                  <span className="hidden sm:inline">Export</span>
                </Button>
                
                {showExportMenu && (
                  <div className="absolute right-0 top-full mt-2 w-48 bg-white rounded-xl border border-border/50 shadow-xl z-50 py-2">
                    <button
                      onClick={() => { exportAsMarkdown(); setShowExportMenu(false); }}
                      className="w-full px-4 py-2 text-left text-sm hover:bg-muted flex items-center gap-2"
                    >
                      <FileText className="w-4 h-4" />
                      Export as Markdown
                    </button>
                    <button
                      onClick={() => { exportAsJSON(); setShowExportMenu(false); }}
                      className="w-full px-4 py-2 text-left text-sm hover:bg-muted flex items-center gap-2"
                    >
                      <Code2 className="w-4 h-4" />
                      Export as JSON
                    </button>
                  </div>
                )}
              </div>
              
              <Button
                variant="ghost"
                size="sm"
                onClick={sharePlan}
                className="gap-1.5"
                title="Share plan"
              >
                <Share2 className="w-4 h-4" />
                <span className="hidden sm:inline">Share</span>
              </Button>
            </div>
          </div>
        </CardHeader>

        <CardContent className="space-y-8 pt-6">
          {/* Problem Statement */}
          <div className="bg-muted/30 rounded-xl p-5 border border-border/50">
            <div className="flex items-center gap-2 mb-3">
              <Lightbulb className="w-4 h-4 text-primary" />
              <span className="text-sm font-semibold text-muted-foreground uppercase tracking-wide">Problem Statement</span>
            </div>
            <p className="text-foreground leading-relaxed">{output.problemStatement?.fullStatement || 'Problem statement not available'}</p>
          </div>

          {/* Market Research Section */}
          <section className="space-y-4">
            <button 
              onClick={() => toggleSection('marketResearch')}
              className="w-full flex items-center justify-between group"
            >
              <div className="flex items-center gap-3">
                <div className="p-2 bg-blue-100 rounded-lg">
                  <TrendingUp className="w-5 h-5 text-blue-600" />
                </div>
                <div>
                  <h3 className="font-semibold text-foreground">Market Research & Analysis</h3>
                  {hasBeenRefined && (
                    <Badge variant="secondary" className="text-xs bg-blue-100 text-blue-700 mt-1">
                      Real 2024-2025 Data
                    </Badge>
                  )}
                </div>
              </div>
              <ChevronRight className={`w-5 h-5 text-muted-foreground transition-transform ${expandedSections.marketResearch ? 'rotate-90' : ''}`} />
            </button>
            
            {expandedSections.marketResearch && (
              <div className="pl-12 space-y-4 animate-in slide-in-from-top-2 duration-300">
                {/* Market Size Cards */}
                <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                  {[
                    { label: 'Total Market (TAM)', value: output.marketResearch?.tam, icon: PieChart },
                    { label: 'Serviceable (SAM)', value: output.marketResearch?.sam, icon: BarChart3 },
                    { label: 'Target (SOM)', value: output.marketResearch?.som, icon: Target },
                  ].map((item, idx) => (
                    <div key={idx} className="bg-gradient-to-br from-blue-50 to-blue-100/50 rounded-xl p-4 border border-blue-200/50 hover-lift">
                      <div className="flex items-center gap-2 mb-2">
                        <item.icon className="w-4 h-4 text-blue-500" />
                        <p className="text-xs font-medium text-blue-600 uppercase tracking-wide">{item.label}</p>
                      </div>
                      <p className="text-lg font-semibold text-foreground">{item.value || 'N/A'}</p>
                    </div>
                  ))}
                </div>

                {/* Growth Rate */}
                <div className="flex items-center gap-3 p-3 bg-blue-50/50 rounded-lg">
                  <Rocket className="w-5 h-5 text-blue-500" />
                  <span className="text-sm font-medium text-blue-700">
                    Growth Rate: {output.marketResearch?.marketGrowthRate || 'N/A'}
                  </span>
                </div>

                {/* Key Trends */}
                <div>
                  <p className="text-sm font-medium text-muted-foreground mb-2">Key Market Trends (2024-2025):</p>
                  <div className="flex flex-wrap gap-2">
                    {output.marketResearch?.keyTrends?.map((trend, idx) => (
                      <Badge key={idx} variant="secondary" className="bg-blue-100 text-blue-700 hover:bg-blue-200 transition-colors">
                        {trend}
                      </Badge>
                    )) || <span className="text-sm text-muted-foreground">No trends data</span>}
                  </div>
                </div>

                <Separator className="bg-border/50" />

                {/* Competitor Analysis */}
                <div>
                  <p className="text-sm font-medium text-muted-foreground mb-3 flex items-center gap-2">
                    <Search className="w-4 h-4" />
                    Competitive Landscape
                  </p>
                  <div className="grid gap-3">
                    {output.marketResearch?.competitorAnalysis?.map((comp, idx) => (
                      <div key={idx} className="bg-white rounded-xl p-4 border border-border/50 shadow-sm hover-lift">
                        <div className="flex items-center justify-between mb-2">
                          <span className="font-semibold text-foreground">{comp.name}</span>
                          <Badge variant="outline" className="text-xs">{comp.marketShare} share</Badge>
                        </div>
                        <div className="grid grid-cols-2 gap-2 text-sm">
                          <div className="flex items-start gap-2">
                            <CheckCircle className="w-4 h-4 text-green-500 mt-0.5 shrink-0" />
                            <span className="text-green-700">{comp.strengths}</span>
                          </div>
                          <div className="flex items-start gap-2">
                            <AlertTriangle className="w-4 h-4 text-amber-500 mt-0.5 shrink-0" />
                            <span className="text-amber-700">{comp.weaknesses}</span>
                          </div>
                        </div>
                        <p className="text-xs text-muted-foreground mt-2">Pricing: {comp.pricing}</p>
                      </div>
                    )) || <span className="text-sm text-muted-foreground">No competitor data</span>}
                  </div>
                </div>

                {/* Demographics & Pain Points */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="bg-muted/30 rounded-xl p-4">
                    <p className="text-sm font-medium text-muted-foreground mb-2 flex items-center gap-2">
                      <Users className="w-4 h-4" />
                      Target Demographics
                    </p>
                    <p className="text-sm text-foreground">{output.marketResearch?.targetDemographics || 'N/A'}</p>
                  </div>
                  <div className="bg-muted/30 rounded-xl p-4">
                    <p className="text-sm font-medium text-muted-foreground mb-2 flex items-center gap-2">
                      <AlertTriangle className="w-4 h-4" />
                      User Pain Points
                    </p>
                    <ul className="space-y-1">
                      {output.marketResearch?.userPainPoints?.map((pain, idx) => (
                        <li key={idx} className="text-sm text-foreground flex items-start gap-2">
                          <span className="text-red-500 mt-0.5">•</span>
                          {pain}
                        </li>
                      )) || <li className="text-sm text-muted-foreground">No pain points data</li>}
                    </ul>
                  </div>
                </div>

                {/* Market Gaps */}
                <div>
                  <p className="text-sm font-medium text-muted-foreground mb-2 flex items-center gap-2">
                    <Lightbulb className="w-4 h-4" />
                    Market Gaps & Opportunities
                  </p>
                  <div className="flex flex-wrap gap-2">
                    {output.marketResearch?.marketGaps?.map((gap, idx) => (
                      <Badge key={idx} variant="outline" className="bg-green-50 text-green-700 border-green-200">
                        {gap}
                      </Badge>
                    )) || <span className="text-sm text-muted-foreground">No market gaps data</span>}
                  </div>
                </div>
              </div>
            )}
          </section>

          <Separator className="bg-border/50" />

          {/* MVP Features */}
          <section className="space-y-4">
            <button 
              onClick={() => toggleSection('mvpFeatures')}
              className="w-full flex items-center justify-between group"
            >
              <div className="flex items-center gap-3">
                <div className="p-2 bg-violet-100 rounded-lg">
                  <Wrench className="w-5 h-5 text-violet-600" />
                </div>
                <div className="flex items-center gap-2">
                  <h3 className="font-semibold text-foreground">MVP Features</h3>
                  {hasBeenRefined && (
                    <Badge variant="secondary" className="text-xs bg-violet-100 text-violet-700">
                      {output.mvpFeatures.length}
                    </Badge>
                  )}
                </div>
              </div>
              <ChevronRight className={`w-5 h-5 text-muted-foreground transition-transform ${expandedSections.mvpFeatures ? 'rotate-90' : ''}`} />
            </button>
            
            {expandedSections.mvpFeatures && (
              <div className="pl-12 space-y-2 animate-in slide-in-from-top-2 duration-300">
                {output.mvpFeatures.map((feature, index) => (
                  <div 
                    key={index} 
                    className="flex items-start gap-3 p-3 rounded-lg bg-muted/30 hover:bg-muted/50 transition-colors group"
                  >
                    <div className="flex-shrink-0 w-6 h-6 rounded-full bg-gradient-to-br from-violet-500 to-fuchsia-500 flex items-center justify-center text-white text-xs font-bold">
                      {index + 1}
                    </div>
                    <span className="text-foreground">{feature}</span>
                  </div>
                ))}
              </div>
            )}
          </section>

          <Separator className="bg-border/50" />

          {/* Tech Stack */}
          <section className="space-y-4">
            <button 
              onClick={() => toggleSection('techStack')}
              className="w-full flex items-center justify-between group"
            >
              <div className="flex items-center gap-3">
                <div className="p-2 bg-cyan-100 rounded-lg">
                  <Layers className="w-5 h-5 text-cyan-600" />
                </div>
                <div className="flex items-center gap-2">
                  <h3 className="font-semibold text-foreground">Free Tech Stack</h3>
                  {hasBeenRefined && (
                    <Badge variant="secondary" className="text-xs bg-cyan-100 text-cyan-700">
                      {output.techStack.length} tools
                    </Badge>
                  )}
                </div>
              </div>
              <ChevronRight className={`w-5 h-5 text-muted-foreground transition-transform ${expandedSections.techStack ? 'rotate-90' : ''}`} />
            </button>
            
            {expandedSections.techStack && (
              <div className="pl-12 grid gap-2 animate-in slide-in-from-top-2 duration-300">
                {output.techStack.map((item, index) => (
                  <div 
                    key={index} 
                    className="flex items-center justify-between p-4 bg-gradient-to-r from-cyan-50/50 to-transparent rounded-xl border border-cyan-200/30 hover-lift"
                  >
                    <div className="flex items-center gap-3">
                      <Badge variant="secondary" className="bg-cyan-100 text-cyan-700">
                        {item.category}
                      </Badge>
                      <span className="font-semibold text-foreground">{item.tool}</span>
                    </div>
                    <span className="text-sm text-muted-foreground">{item.purpose}</span>
                  </div>
                ))}
              </div>
            )}
          </section>

          <Separator className="bg-border/50" />

          {/* Build Plan */}
          <section className="space-y-4">
            <button 
              onClick={() => toggleSection('buildPlan')}
              className="w-full flex items-center justify-between group"
            >
              <div className="flex items-center gap-3">
                <div className="p-2 bg-amber-100 rounded-lg">
                  <Hammer className="w-5 h-5 text-amber-600" />
                </div>
                <div className="flex items-center gap-2">
                  <h3 className="font-semibold text-foreground">Step-by-Step Build Plan</h3>
                  {hasBeenRefined && (
                    <Badge variant="secondary" className="text-xs bg-amber-100 text-amber-700">
                      {output.buildPlan.length} steps
                    </Badge>
                  )}
                </div>
              </div>
              <ChevronRight className={`w-5 h-5 text-muted-foreground transition-transform ${expandedSections.buildPlan ? 'rotate-90' : ''}`} />
            </button>
            
            {expandedSections.buildPlan && (
              <div className="pl-12 space-y-3 animate-in slide-in-from-top-2 duration-300">
                {output.buildPlan.map((step, index) => (
                  <div 
                    key={index} 
                    className="flex gap-4 p-4 bg-gradient-to-r from-amber-50/30 to-transparent rounded-xl border border-amber-200/30 hover-lift"
                  >
                    <div className="flex-shrink-0 w-10 h-10 bg-gradient-to-br from-amber-500 to-orange-500 text-white rounded-xl flex items-center justify-center font-bold shadow-md">
                      {step.step}
                    </div>
                    <div className="flex-1 space-y-2">
                      <h4 className="font-semibold text-foreground">{step.title}</h4>
                      <p className="text-sm text-muted-foreground">{step.description}</p>
                      <div className="flex items-center gap-4 text-sm text-muted-foreground">
                        <span className="flex items-center gap-1">
                          <Clock className="w-4 h-4" />
                          {step.estimatedTime}
                        </span>
                      </div>
                      {step.aiToolAction && (
                        <div className="mt-2 p-3 bg-gradient-to-r from-violet-50 to-fuchsia-50 border border-violet-200 rounded-lg">
                          <div className="flex items-center gap-2 mb-1">
                            <Brain className="w-4 h-4 text-violet-600" />
                            <span className="text-xs font-semibold text-violet-700">AI Action</span>
                          </div>
                          <p className="text-sm text-violet-800">{step.aiToolAction}</p>
                        </div>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            )}
          </section>

          <Separator className="bg-border/50" />

          {/* Monetization */}
          <section className="space-y-4">
            <button 
              onClick={() => toggleSection('monetization')}
              className="w-full flex items-center justify-between group"
            >
              <div className="flex items-center gap-3">
                <div className="p-2 bg-green-100 rounded-lg">
                  <DollarSign className="w-5 h-5 text-green-600" />
                </div>
                <h3 className="font-semibold text-foreground">Monetization Strategy</h3>
              </div>
              <ChevronRight className={`w-5 h-5 text-muted-foreground transition-transform ${expandedSections.monetization ? 'rotate-90' : ''}`} />
            </button>
            
            {expandedSections.monetization && (
              <div className="pl-12 space-y-4 animate-in slide-in-from-top-2 duration-300">
                <div className="bg-gradient-to-br from-green-50 to-emerald-50 rounded-xl p-5 border border-green-200/50">
                  <div className="flex items-center justify-between mb-4">
                    <span className="text-sm font-medium text-muted-foreground">Revenue Model</span>
                    <Badge className="bg-green-100 text-green-800 hover:bg-green-100">
                      {output.monetizationStrategy.model}
                    </Badge>
                  </div>
                  
                  <div className="space-y-3">
                    <div className="flex items-start gap-3">
                      <div className="p-1.5 bg-green-200 rounded">
                        <DollarSign className="w-4 h-4 text-green-700" />
                      </div>
                      <div>
                        <p className="text-sm font-medium text-foreground">Pricing Structure</p>
                        <p className="text-sm text-muted-foreground">{output.monetizationStrategy.pricing}</p>
                      </div>
                    </div>
                    
                    <div className="flex items-start gap-3">
                      <div className="p-1.5 bg-green-200 rounded">
                        <TrendingUp className="w-4 h-4 text-green-700" />
                      </div>
                      <div>
                        <p className="text-sm font-medium text-foreground">Revenue Projection</p>
                        <p className="text-sm text-muted-foreground">{output.monetizationStrategy.revenueEstimate}</p>
                      </div>
                    </div>
                  </div>

                  <Separator className="my-4 bg-green-200" />
                  
                  <p className="text-sm font-medium text-foreground mb-3">First User Acquisition Tactics:</p>
                  <div className="grid gap-2">
                    {output.monetizationStrategy.firstUserTactics.map((tactic, index) => (
                      <div key={index} className="flex items-center gap-3 text-sm">
                        <div className="w-5 h-5 rounded-full bg-green-200 flex items-center justify-center">
                          <Check className="w-3 h-3 text-green-700" />
                        </div>
                        <span className="text-foreground">{tactic}</span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            )}
          </section>
        </CardContent>
      </Card>

      {/* Refinement CTA */}
      <Card className="border-primary/20 bg-gradient-to-br from-primary/5 via-primary/10 to-primary/5 shadow-xl shadow-primary/10 overflow-hidden">
        <CardContent className="py-8">
          <div className="flex flex-col items-center gap-5 text-center">
            <div className="relative">
              <div className="p-4 bg-gradient-to-br from-primary to-primary/80 rounded-2xl shadow-lg shadow-primary/30">
                <Wand2 className="w-8 h-8 text-white" />
              </div>
              <div className="absolute -top-2 -right-2 w-6 h-6 bg-gradient-to-br from-amber-400 to-orange-500 rounded-full flex items-center justify-center">
                <Sparkles className="w-3.5 h-3.5 text-white" />
              </div>
            </div>
            
            <div className="space-y-2">
              <h3 className="text-xl font-bold text-foreground">
                Want an Even More Comprehensive Plan?
              </h3>
              <p className="text-muted-foreground max-w-lg">
                {hasBeenRefined 
                  ? `This plan has been refined ${iterationCount} time${iterationCount !== 1 ? 's' : ''}. Each refinement adds more detail, better structure, and actionable insights.`
                  : "Transform this into a meticulously-crafted, publication-quality blueprint with endless refinement iterations."
                }
              </p>
            </div>
            
            <Button
              onClick={onRefine}
              className="gap-2 bg-gradient-to-r from-primary to-primary/90 hover:from-primary/90 hover:to-primary text-white px-8 py-6 text-base font-semibold shadow-lg shadow-primary/30 hover:shadow-xl hover:shadow-primary/40 hover:-translate-y-0.5 transition-all duration-300 btn-shine"
            >
              <Sparkles className="w-5 h-5" />
              {hasBeenRefined 
                ? `Refine Again (Iteration #${iterationCount + 1})` 
                : "✨ Refine for Masterclass Quality"
              }
              <ArrowRight className="w-5 h-5" />
            </Button>
            
            <p className="text-xs text-muted-foreground">
              Each click creates: very-well-planned • logically-built • visually-mapped • meticulously-crafted
            </p>
          </div>
        </CardContent>
      </Card>

      {/* Feedback Section */}
      <Card className="border-border/50 bg-white/80 backdrop-blur-xl">
        <CardContent className="py-6">
          {!feedbackSubmitted ? (
            <div className="flex flex-col items-center gap-4">
              <p className="text-foreground font-medium">Was this plan helpful?</p>
              <div className="flex gap-3">
                <Button
                  variant="outline"
                  onClick={() => handleFeedback(true)}
                  className="gap-2 hover:bg-green-50 hover:border-green-300 hover:text-green-700 transition-all duration-300"
                >
                  <ThumbsUp className="w-4 h-4" />
                  Yes, helpful
                </Button>
                <Button
                  variant="outline"
                  onClick={() => handleFeedback(false)}
                  className="gap-2 hover:bg-red-50 hover:border-red-300 hover:text-red-700 transition-all duration-300"
                >
                  <ThumbsDown className="w-4 h-4" />
                  Not helpful
                </Button>
              </div>
            </div>
          ) : (
            <div className="text-center text-green-600 fade-in-up">
              <div className="inline-flex items-center justify-center w-12 h-12 bg-green-100 rounded-full mb-3">
                <Check className="w-6 h-6" />
              </div>
              <p className="font-medium">Thanks for your feedback!</p>
              <p className="text-sm text-muted-foreground">This helps FoundryAI improve.</p>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
