name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: team_13jt5sWRe2sBUcvwdid10Ntn
          vercel-project-id: prj_hmDbcl8TEQ0NBSZepUudNxGkFWHQ
          vercel-args: '--prod'
